version: "3.9"
services:
  postgres:
    image: postgres:17
    container_name: postgres_order
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_control
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: always
  
  redis:
    image: redis:7
    container_name: redis_order
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/castilho/development/src/order-control/postgres/data