version: "3.9"
services:
  db:
    image: postgres:17
    container_name: postgres_order
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_control
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/castilho/development/src/order-control/postgres/data